### ISSUE TITLE
Launching the project

### ISSUE THREAD

**Issue by carlos-rodriguez-peralta** [KozhinovAlexander/zephyr_vscode_workspace#2]
Hello Alexander!
I follow your guide and everything was perfect until I got this message after pressing F5 to debug.

<`OpenOCD GDB executable "/home/carlos/zephyr-sdk-0.12.2/arm-zephyr-eabi/bin/arm-none-eabi-gdb" was not found. Please configure "cortex-debug.armToolcahinPath" or "cortex-debug.gdbPath" correctly`>

Do you know how to solve it? 

(by the way, awesome repository!!! )

**Comment by KozhinovAlexander** [comment]
Hello Carlos,

Thank your for your feedback.

> Hello Alexander!
> I follow your guide and everything was perfect until I got this message after pressing F5 to debug.
> 

I am happy, that it works for you :) 

> <`OpenOCD GDB executable "/home/carlos/zephyr-sdk-0.12.2/arm-zephyr-eabi/bin/arm-none-eabi-gdb" was not found. Please configure "cortex-debug.armToolcahinPath" or "cortex-debug.gdbPath" correctly`>
> 

The reason for that, that ARM Cortex-M debug extension from Visual Studio Code expects debugger by the name `arm-none-eabi-gdb`. But currently it can not be changed from extension's settings. And Zephyr calls it's debugger: `arm-zephyr-eabi-gdb`

> Do you know how to solve it?
> 

Sure. Just create symbolic link by doing following from your terminal:

```bash
cd /home/carlos/zephyr-sdk-0.12.2/arm-zephyr-eabi/bin
ln -s arm-zephyr-eabi-gdb arm-none-eabi-gdb
```

Typing now `ln -s arn-*-eabi-gdb` should give you:

```
lrwxrwxrwx 1 <your-user-name-here> <your-user-name-here>      19 Feb 27 18:15 arm-none-eabi-gdb -> arm-zephyr-eabi-gdb
```

First `l` letter means it is a link ;) You're welcome to create PR with description of this solution :)

> (by the way, awesome repository!!! )

Thank you :)

**Comment by carlos-rodriguez-peralta** [comment]
It works!! Thank you! (I tried to create a PR but I got an error. Maybe I dont have permission to fork.
